clean:
	$(MAKE) clean --directory=lib_base_trie
	$(MAKE) clean --directory=lib_pointer_mem
	$(MAKE) clean --directory=utils/string
	$(MAKE) clean --directory=lib_trie_info
	$(MAKE) clean --directory=lib_value_int

test:
	$(MAKE) test --directory=utils/string
	$(MAKE) test --directory=base/trie
